### ISSUE TITLE
Title is the issue

### ISSUE THREAD

**Issue by muzammil9900** [PyExplained/Autotune-using-Python#1]
Its showing like this>
File "c:\Users\Muzammil\Desktop\Autotune-using-Python\autotune\Autotune.py", line 31, in __init__     
    self.fig.canvas.set_window_title('AutoTune')
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

so i removed it and now its running
 # self.fig.canvas.set_window_title('AutoTune')

**Comment by PyExplained** [comment]
Thanks for informing me about this bug. I have only tried running it in Python 3.8 and matplotlib version 3.1.2, but maybe you're using a newer version? So far, I haven't found any changes in the matplotlib documentation regarding the set_window_title command, but I may have overlooked something.
For now, the best thing I can recommend for people having this issue is indeed removing the line of code entirely. I will however try to find a better solution, but it might help to know which version you're using.
